-- Riwayat aktivitas untuk panel admin. Seluruh penulisan dilakukan dari server
-- menggunakan service-role key; anon dan authenticated tidak diberi akses.
create table if not exists public.admin_activity (
  id bigint generated by default as identity primary key,
  module text not null,
  action text not null check (action in ('create', 'update', 'delete')),
  title text not null,
  entity_id text,
  created_at timestamptz not null default now()
);

create index if not exists admin_activity_created_at_idx
  on public.admin_activity (created_at desc);

alter table public.admin_activity enable row level security;

revoke all on table public.admin_activity from anon, authenticated;
revoke all on sequence public.admin_activity_id_seq from anon, authenticated;
